### ISSUE TITLE
Switch decimals of liquidity token from 0 to 6

### ISSUE THREAD

**Issue by purcell** [tezos-checker/checker#146]
Seems more idiomatic (or at least more consistent) to have fractional liquidity, so let's go ahead and change this. See https://tezos-dev.slack.com/archives/G01AAK05N86/p1622727161020300?thread_ts=1622016921.002500&cid=G01AAK05N86

**Comment by gkaracha** [comment]
Ah, yes, we could do that. In fact, this is totally a GUI thing I believe, the internal logic can probably remain as is.

**Comment by dorranh** [comment]
@gkaracha, when I briefly looked at this yesterday, I noticed that we don't use any scaling factors in our calculations with liquidity. Would this mean that we would have to update our calculations if we increase the decimals to 6?

**Comment by gkaracha** [comment]
Hmmmm, I am not entirely sure, but I think quite the opposite (could be wrong), since (conceptually) we are already dealing with mulqt so we are using maximum precision. Increasing the scaling factor from 1 to 1_000_000 I think then just changes our current 423 into 0.000423, but that's just looks. Going the other way would be the problem: decreasing the scaling factor from 1_000_000 to 1: then values such as our current 423 become zero and we have precision loss.

**Comment by gkaracha** [comment]
@dorranh Yes, you're absolutely right. So, this change will affect fractions with other things, if one were to calculate the price of lqt against other things (and indeed that's why we currently have all the scaling factors going around). For the sake of completeness of the discussion, here's how I think about it:

If, for example, we had to calculate the price of USD/lqt by dividing two amounts (like we do in cfmm for example, to calculate the price of kit in tez), the problem would probably become apparent. Say:
```
amount_usd = 300 (scaling_factor_usd = 100, so basically $3)
amount_lqt =   1 (scaling_factor_lqt = 1)
```
So the price inferred is $3 per 1 lqt.

Now, if we want to treat that 1lqt as 1mulqt instead, then the price would have to rise to $300_000_000 per 1 lqt, but if we don't add the scaling factor in our calculations the price won't change (though it should).

So, the bottom line is that because we don't compute such fractions currently (so probably no test will break by adding the scaling factor, but we'll see about that) there will be no real code changes. However, adding (and using) the scaling factor seems _the-right-thing-to-do_, so I'll go ahead and self-assign this one. I'll make the `liquidity` opaque and follow the trail of errors to see if there are any actual changes to be made.

**Comment by gkaracha** [comment]
Sidenote: I now also see that in the codebase we have named the conversion functions `kit_to_mukit_nat`/`kit_of_mukit`, which doesn't really agree with the idea that the scaling factor could change (might become nano, micro, ..). We probably should find a more generic name (`_to_units` or something?).
