### ISSUE TITLE
Potential security vulnerabilities in the python dependencies

### ISSUE THREAD

**Issue by gkaracha** [tezos-checker/checker#278]
Since #272 was merged I've been seeing the following Dependabot warning:
```
We found potential security vulnerabilities in your dependencies.
```
[The warning](https://github.com/tezos-checker/checker/security/dependabot) refers to two python dependencies in our `poetry.lock`:
- [x] [fastecdsa](https://github.com/tezos-checker/checker/security/dependabot/poetry.lock/fastecdsa/open)
- [ ] [pywin32](https://github.com/tezos-checker/checker/security/dependabot/poetry.lock/pywin32/open)

We should probably fix that.

**Comment by dorranh** [comment]
The first point is actually a bit blocked by pytezos which pins an older version of fastecdsa. We can hack around that need be, but the cleaner solution is to upgrade it upstream. I created an issue for this here: https://github.com/baking-bad/pytezos/issues/261

**Comment by dorranh** [comment]
The `pywin32` one is an issue with both our version of `docker-py` and that used by `pytezos`. However, we can't bump our `docker-py` version to the latest release (`5.0.3`) until `pytezos` upgrades since `pytezos` places an upper bound of `<5.0.0`.

**Comment by dorranh** [comment]
Note: the `pywin32` vulnerability is blocked on https://github.com/docker/docker-py/pull/2925.

**Comment by dorranh** [comment]
After reviewing the pywin32 vulnerability a bit more, it seems that this should only affect people running checker's python applications directly on Windows (i.e. on the Windows host itself and not from within a Docker container running on Windows). Since very few of the tools in our stack are supported on Windows, I'm going to go ahead and dismiss that alert. Please feel free to re-open though.

**Comment by gkaracha** [comment]
Sounds good to me! :+1:
